src/Entity/soc/Societe.php
<?php

namespace App\Entity\soc;

use App\Repository\SocieteRepository;
use App\Entity\Client;
use App\Entity\User;
use App\Entity\Produit;
use App\Entity\Paiement;
use App\Entity\FactureProduit;
use App\Entity\Facture;
use App\Entity\DevisProduit;
use App\Entity\Devis;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;


#[ORM\Entity(repositoryClass: SocieteRepository::class)]
#[ORM\Table(name: '`societe`')]
#[Vich\Uploadable]
class Societe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La raison sociale est obligatoire.")]
    private ?string $raison_sociale = null;

    #[ORM\Column(unique: true)]
    #[Gedmo\Slug(fields: ['raison_sociale'])]
    private ?string $slug = null;

    #[ORM\Column]
    #[Assert\NotNull(message: "Le numéro de SIRET est obligatoire.")]
    private ?int $num_siret = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Regex(
        pattern: "/^\d{5}$/",
        message: "Le code postal doit contenir 5 chiffres."
    )]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "La ville est obligatoire.")]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "L'email est obligatoire.")]
    #[Assert\Email(
        message: "L'adresse email n'est pas une adresse email valide."
    )]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Regex(
        pattern: "/^\d{9}$/",
        message: "Le numéro de téléphone doit contenir 9 chiffres."
    )]
    private ?string $num_tel = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Regex(
        pattern: "/^\d{9}$/",
        message: "Le numéro de téléphone fixe doit contenir 9 chiffres."
    )]
    private ?string $num_fix = null;

    #[Vich\UploadableField(mapping: 'avatar_logo_societe', fileNameProperty: 'avatar_logo')]
    private ?File $avatar_logoFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $avatar_logo = null;

    #[Gedmo\Timestampable(on: 'create')]
    #[ORM\Column(type: 'datetime', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private \DateTime $createdAt;

    #[Gedmo\Timestampable(on: 'update')]
    #[ORM\Column(type: 'datetime', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private \DateTime $updatedAt;

    #[Gedmo\Blameable(on: 'create')]
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $createdBy = null;

    #[Gedmo\Blameable(on: 'update')]
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $updatedBy = null;


    #[ORM\OneToMany(mappedBy: 'society', targetEntity: Client::class, orphanRemoval: true)]
    private Collection $clients;

    #[ORM\OneToMany(mappedBy: 'society', targetEntity: Produit::class, orphanRemoval: true)]
    private Collection $produits;

    #[ORM\OneToMany(mappedBy: 'society', targetEntity: Devis::class, orphanRemoval: true)]
    private Collection $devis;

    #[ORM\OneToMany(mappedBy: 'society', targetEntity: Facture::class, orphanRemoval: true)]
    private Collection $factures;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'societe_id')]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->clients = new ArrayCollection();
        $this->produits = new ArrayCollection();
        $this->devis = new ArrayCollection();
        $this->factures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(string $raison_sociale): static
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getNumSiret(): ?int
    {
        return $this->num_siret;
    }

    public function setNumSiret(int $num_siret): static
    {
        $this->num_siret = $num_siret;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(?string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getNumFix(): ?string
    {
        return $this->num_fix;
    }

    public function setNumFix(?string $num_fix): static
    {
        $this->num_fix = $num_fix;

        return $this;
    }

    public function getAvatarLogo(): ?string
    {
        return $this->avatar_logo;
    }

    public function setAvatarLogo(?string $avatar_logo): static
    {
        $this->avatar_logo = $avatar_logo;

        return $this;
    }

    public function setAvatarLogoFile(?File $avatar_logoFile = null): void
    {
        $this->avatar_logoFile = $avatar_logoFile;

        if (null !== $avatar_logoFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function getAvatarLogoFile(): ?File
    {
        return $this->avatar_logoFile;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string|null $slug
     * @return self
     */
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return Collection<int, Client>
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): static
    {
        if (!$this->clients->contains($client)) {
            $this->clients->add($client);
            $client->setSociety($this);
        }

        return $this;
    }

    public function removeClient(Client $client): static
    {
        if ($this->clients->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getSociety() === $this) {
                $client->setSociety(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setSociety($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            if ($produit->getSociety() === $this) {
                $produit->setSociety(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): static
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setSociety($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): static
    {
        if ($this->devis->removeElement($devi)) {
            if ($devi->getSociety() === $this) {
                $devi->setSociety(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): static
    {
        if (!$this->factures->contains($facture)) {
            $this->factures->add($facture);
            $facture->setSociety($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): static
    {
        if ($this->factures->removeElement($facture)) {
            if ($facture->getSociety() === $this) {
                $facture->setSociety(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addSocieteId($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeSocieteId($this);
        }

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

src/Form/SocieteType.php
<?php

namespace App\Form;

use App\Entity\soc\Societe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class SocieteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raison_sociale')
            ->add('num_siret')
            ->add('adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('email')
            ->add('num_tel')
            ->add('num_fix')
            ->add('avatar_logoFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'Supprimer',
                'download_label' => 'Télécharger',
                'download_uri' => true,
                'image_uri' => true,
                'asset_helper' => true,
            ])
            // ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Societe::class,
        ]);
    }
}

src/Controller/SocieteController.php
<?php

namespace App\Controller;

use App\Entity\soc\Societe;
use App\Form\SocieteType;
use App\Repository\SocieteRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

#[Route('/societe')]
class SocieteController extends AbstractController
{
    #[Route('/', name: 'app_societe_index', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function index(SocieteRepository $societeRepository, Request $request): Response
    {
        $user = $this->getUser();
        $currentPage = $request->query->getInt('page', 1);
        $limit = 6;
        $search = $request->query->get('search');

        $societes = $societeRepository->findByCriteriaWithPagination($user, $search, $currentPage, $limit);
        $maxPages = ceil(count($societes) / $limit);

        return $this->render('societe/index.html.twig', [
            'societes' => $societes,
            'maxPages' => $maxPages,
            'currentPage' => $currentPage,
            'search' => $search,
        ]);
    }

    #[Route('/new', name: 'app_societe_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $societe = new Societe();
        $form = $this->createForm(SocieteType::class, $societe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser(); 

            if ($user) {
                $societe->addUser($user); 
            }

            $entityManager->persist($societe);
            $entityManager->flush();

            return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('societe/new.html.twig', [
            'societe' => $societe,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_societe_show', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function show(Societe $societe): Response
    {
        return $this->render('societe/show.html.twig', [
            'societe' => $societe,
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_societe_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Societe $societe, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SocieteType::class, $societe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('societe/edit.html.twig', [
            'societe' => $societe,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_societe_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Societe $societe, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$societe->getId(), $request->request->get('_token'))) {
            $entityManager->remove($societe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_societe_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/societe-info/{id}', name: 'societe_info', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function getSocieteInfo(SocieteRepository $repository, int $id): JsonResponse
    {
        $societe = $repository->find($id);
        
        if (!$societe) {
            return new JsonResponse(['error' => 'Société non trouvée'], 404);
        }

        $data = [
            'raison_sociale' => $societe->getRaisonSociale(),
            'adresse' => $societe->getAdresse(),
            'code_postal' => $societe->getCodePostal(),
            'ville' => $societe->getVille(),
            'num_tel' => $societe->getNumTel(),
        ];

        return new JsonResponse($data);
    }
    #[Route('/api/societe/{id}/clients', name: 'api_societe_clients')]
    #[IsGranted('ROLE_USER')]
    public function getClientsBySociete(Societe $societe): JsonResponse
    {
        $clients = [];
        foreach ($societe->getClients() as $client) {
            $label = $client->getType() === 'entreprise' 
                    ? $client->getRaisonSociale() 
                    : $client->getNom() . ' ' . $client->getPrenom();
            $clients[] = [
                'id' => $client->getId(),
                'label' => $label, 
            ];
        }
        return $this->json($clients);
    }

}

templates/societe/_delete_form.html.twig
<form method="post" action="{{ path('app_societe_delete', {'id': societe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ societe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/societe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index des Sociétés{% endblock %}

{% block body %}
{% include 'components/navbar.html.twig' %}
<div class="flex mt-4">
    {% include 'components/sidebar.html.twig' %}
    <div class="ml-4 mr-4 flex-1 p-4 overflow-x-auto dark:bg-gray-800 content bg-white p-4 rounded-lg shadow">
        <h1 class="text-blue-color font-nunito text-lg font-bold dark:text-white mb-4">Gérer les sociétés</h1>
        <div class="mb-4">
            <form action="{{ path('app_societe_index') }}" method="get" class="flex items-center space-x-2">
                <input type="text" name="search" placeholder="Rechercher par raison sociale" class="flex-1 border p-2 rounded-lg text-black dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400 w-full sm:w-auto sm:flex-1">
                <button type="submit" class="p-2 bg-blue-color text-white rounded-lg flex items-center justify-center w-12 h-12 sm:w-auto sm:h-auto sm:p-2">
                    <i class="fas fa-search text-white text-lg"></i>
                    <span class="ml-2 hidden sm:block">Rechercher</span>
                </button>
            </form>
        </div>
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-white font-nunito uppercase bg-blue-color">
                    <tr>
                        <th scope="col" class="px-6 py-3">Raison Sociale</th>
                        <th scope="col" class="px-6 py-3">Num SIRET</th>
                        <th scope="col" class="px-6 py-3">Num Tel</th>
                        <th scope="col" class="px-6 py-3">Créé Le</th>
                        <th scope="col" class="px-6 py-3">Créé Par</th>
                        <th scope="col" class="px-6 py-3">Modifié Le</th>
                        <th scope="col" class="px-6 py-3">Modifié Par</th>
                        <th scope="col" class="px-6 py-3">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for societe in societes %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <td class="px-6 py-4">{{ societe.raisonSociale }}</td>
                        <td class="px-6 py-4">{{ societe.numSiret }}</td>
                        <td class="px-6 py-4">{{ societe.numTel }}</td>
                        <td class="px-6 py-4">{{ societe.createdAt ? societe.createdAt|date('Y-m-d') : '' }}</td>
                        <td class="px-6 py-4">{{ societe.createdBy ? societe.createdBy.email : 'N/A' }}</td>
                        <td class="px-6 py-4">{{ societe.updatedAt ? societe.updatedAt|date('Y-m-d') : '' }}</td>
                        <td class="px-6 py-4">{{ societe.updatedBy ? societe.updatedBy.email : 'N/A' }}</td>
                        <td class="px-6 py-4 flex space-x-2">
                            <a href="{{ path('app_societe_show', {'slug': societe.slug}) }}" class="font-medium text-blue-600 hover:underline dark:text-blue-300">Voir</a>
                            <a href="{{ path('app_societe_edit', {'slug': societe.slug}) }}" class="font-medium text-blue-600 hover:underline dark:text-blue-300">Modifier</a>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="8" class="px-6 py-4 text-center dark:text-white">Aucune société trouvée</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="paginationControls" class="flex justify-center mt-4 space-x-2">
            {% if currentPage > 1 %}
                <a href="{{ path('app_societe_index', {'page': currentPage - 1}) }}" class="text-blue-color hover:text-blue-800 dark:text-white">
                    <i class="fas fa-arrow-left"></i>
                </a>
            {% endif %}
            <span class="text-blue-color dark:text-white">{{ currentPage }}</span>
            {% if currentPage < maxPages %}
                <a href="{{ path('app_societe_index', {'page': currentPage + 1}) }}" class="text-blue-color hover:text-blue-800 dark:text-white">
                    <i class="fas fa-arrow-right"></i>
                </a>
            {% endif %}
        </div>

        <div class="mt-4">
            <a href="{{ path('app_societe_new') }}" class="px-4 py-2 bg-blue-color text-white rounded-lg float-right dark:text-gray-200">Créer une nouvelle société</a>
        </div>
    </div>
</div>
{% endblock %}

templates/societe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une nouvelle société{% endblock %}

{% block body %}
    {% include 'components/navbar.html.twig' %}

    <div class="flex mt-4 ml-2 items-start">
        {% include 'components/sidebar.html.twig' %} 

        <div class="flex-1 p-4 ml-4 mr-4 overflow-x-auto dark:bg-gray-800 content bg-white p-4 rounded-lg shadow">
            <h1 class="text-blue-color font-nunito text-lg font-bold mb-2 dark:text-white">Ajouter une nouvelle société</h1>

            <div>
                {{ include('societe/_form.html.twig') }}
            </div>

            <a href="{{ path('app_societe_index') }}" class="text-blue-color dark:text-white">
                <i class="fas fa-arrow-left"></i> Retour
            </a>

        </div>
    </div>
{% endblock %}

templates/societe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de la Société{% endblock %}

{% block body %}
    {% include 'components/navbar.html.twig' %}

    <div class="flex mt-4 ml-2">
        {% include 'components/sidebar.html.twig' %}

        <div class="flex-1 p-4 content bg-white dark:bg-gray-800 p-2 rounded-lg mr-4 ml-2 overflow-x-auto">
            <h1 class="text-blue-color font-nunito text-lg font-bold mb-2 dark:text-white">Détails de la Société</h1>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-4">
                <div class="w-full">
                    <div class="flex justify-center items-center mb-4">
                        <div class="relative">
                            <img src="{{ societe.avatarLogo ? asset('uploads/societe/avatar_logo/' ~ societe.avatarLogo) : asset('images/company_default.png') }}" class="rounded-full border border-gray-200 w-36 h-36 object-cover">
                        </div>
                    </div>
                </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Raison Sociale</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.raisonSociale }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Numéro SIRET</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.numSiret }}</div>
                </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Adresse</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.adresse }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Code Postal</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.codePostal }}</div>
                </div>
            </div>

             <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Ville</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.ville }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Email</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.email }}</div>
                </div>
            </div>


            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Numéro de Téléphone</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.numTel }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Numéro Fixe</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ societe.numFix }}</div>
                </div>
            </div>

            <div class="text-left mt-4">
                <a href="{{ path('app_societe_index') }}" class="text-blue-color dark:text-white">
                    <i class="fas fa-arrow-left"></i> Retour
                </a>
            </div>
        </div>
    </div>
{% endblock %}