src/Entity/FactureProduit.php
<?php

namespace App\Entity;

use App\Repository\FactureProduitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FactureProduitRepository::class)]
class FactureProduit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'factureProduits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Facture $facture = null;

    #[ORM\ManyToOne(inversedBy: 'factureProduits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produit $product = null;

    #[ORM\Column]
    private ?int $nb_apprenant = null;

    #[ORM\Column]
    private ?float $montant_ht = null;

    #[ORM\Column]
    private ?float $taxe_tva = null;

    #[ORM\Column]
    private ?float $montant_remise = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFacture(): ?Facture
    {
        return $this->facture;
    }

    public function setFacture(?Facture $facture): static
    {
        $this->facture = $facture;

        return $this;
    }

    public function getProduct(): ?Produit
    {
        return $this->product;
    }

    public function setProduct(?Produit $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getNbApprenant(): ?int
    {
        return $this->nb_apprenant;
    }

    public function setNbApprenant(int $nb_apprenant): static
    {
        $this->nb_apprenant = $nb_apprenant;

        return $this;
    }

    public function getMontantHt(): ?float
    {
        return $this->montant_ht;
    }

    public function setMontantHt(float $montant_ht): static
    {
        $this->montant_ht = $montant_ht;

        return $this;
    }

    public function getTaxeTva(): ?float
    {
        return $this->taxe_tva;
    }

    public function setTaxeTva(float $taxe_tva): static
    {
        $this->taxe_tva = $taxe_tva;

        return $this;
    }

    public function getMontantRemise(): ?float
    {
        return $this->montant_remise;
    }

    public function setMontantRemise(float $montant_remise): static
    {
        $this->montant_remise = $montant_remise;

        return $this;
    }
}

src/Form/FactureProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\FactureProduit;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;



class FactureProduitType extends AbstractType
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager; 
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        

        $builder
            ->add('product', EntityType::class, [
                'class' => Produit::class,
                'choice_label' => 'designation',  // Remplacez par le champ correct pour l'affichage dans la liste
                'placeholder' => 'Sélectionner un produit',
            ])
            ->add('nb_apprenant')
            ->add('montant_ht')
            ->add('taxe_tva')
            ->add('montant_remise')

            // Ajoutez un événement pour mettre à jour le prix unitaire en fonction du produit choisi
            ->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
                $form = $event->getForm();
                $data = $event->getData();

                // Vérifiez si le produit est sélectionné
                if (isset($data['produit'])) {
                    // Récupérez le produit à partir de la base de données
                    $produit = $this->entityManager->getRepository(Produit::class)->find($data['produit']);

                    // Mettez à jour le prix unitaire dans le formulaire
                    $form->get('priceUnit')->setData($produit->getPriceUnit());
                }
            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FactureProduit::class,
            'allow_extra_fields' => true,
        ]);
    }
}

src/Controller/FactureProduitController.php
<?php

namespace App\Controller;

use App\Entity\FactureProduit;
use App\Form\FactureProduitType;
use App\Repository\FactureProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/facture/produit')]
class FactureProduitController extends AbstractController
{
    #[Route('/', name: 'app_facture_produit_index', methods: ['GET'])]
    public function index(FactureProduitRepository $factureProduitRepository): Response
    {
        return $this->render('facture_produit/index.html.twig', [
            'facture_produits' => $factureProduitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_facture_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $factureProduit = new FactureProduit();
        $form = $this->createForm(FactureProduitType::class, $factureProduit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($factureProduit);
            $entityManager->flush();

            return $this->redirectToRoute('app_facture_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture_produit/new.html.twig', [
            'facture_produit' => $factureProduit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facture_produit_show', methods: ['GET'])]
    public function show(FactureProduit $factureProduit): Response
    {
        return $this->render('facture_produit/show.html.twig', [
            'facture_produit' => $factureProduit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_facture_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FactureProduit $factureProduit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FactureProduitType::class, $factureProduit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_facture_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture_produit/edit.html.twig', [
            'facture_produit' => $factureProduit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facture_produit_delete', methods: ['POST'])]
    public function delete(Request $request, FactureProduit $factureProduit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factureProduit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($factureProduit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_facture_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/facture_produit/_delete_form.html.twig
<form method="post" action="{{ path('app_facture_produit_delete', {'id': facture_produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture_produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/facture_produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/facture_produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FactureProduit{% endblock %}

{% block body %}
    <h1>Edit FactureProduit</h1>

    {{ include('facture_produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_facture_produit_index') }}">back to list</a>

    {{ include('facture_produit/_delete_form.html.twig') }}
{% endblock %}

templates/facture_produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureProduit index{% endblock %}

{% block body %}
    <h1>FactureProduit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nb_apprenant</th>
                <th>Montant_ht</th>
                <th>Taxe_tva</th>
                <th>Montant_remise</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture_produit in facture_produits %}
            <tr>
                <td>{{ facture_produit.id }}</td>
                <td>{{ facture_produit.nbApprenant }}</td>
                <td>{{ facture_produit.montantHt }}</td>
                <td>{{ facture_produit.taxeTva }}</td>
                <td>{{ facture_produit.montantRemise }}</td>
                <td>
                    <a href="{{ path('app_facture_produit_show', {'id': facture_produit.id}) }}">show</a>
                    <a href="{{ path('app_facture_produit_edit', {'id': facture_produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_facture_produit_new') }}">Create new</a>
{% endblock %}

templates/facture_produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FactureProduit{% endblock %}

{% block body %}
    <h1>Create new FactureProduit</h1>

    {{ include('facture_produit/_form.html.twig') }}

    <a href="{{ path('app_facture_produit_index') }}">back to list</a>
{% endblock %}

templates/facture_produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureProduit{% endblock %}

{% block body %}
    <h1>FactureProduit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture_produit.id }}</td>
            </tr>
            <tr>
                <th>Nb_apprenant</th>
                <td>{{ facture_produit.nbApprenant }}</td>
            </tr>
            <tr>
                <th>Montant_ht</th>
                <td>{{ facture_produit.montantHt }}</td>
            </tr>
            <tr>
                <th>Taxe_tva</th>
                <td>{{ facture_produit.taxeTva }}</td>
            </tr>
            <tr>
                <th>Montant_remise</th>
                <td>{{ facture_produit.montantRemise }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_facture_produit_index') }}">back to list</a>

    <a href="{{ path('app_facture_produit_edit', {'id': facture_produit.id}) }}">edit</a>

    {{ include('facture_produit/_delete_form.html.twig') }}
{% endblock %}