src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use App\Entity\soc\Societe;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length:10, nullable: true)]
    private ?string $num_tel = null;

    #[ORM\Column(length:10, nullable: true)]
    private ?string $num_fix = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $raison_sociale = null;

    #[ORM\Column (length: 14, nullable: true)]
    private ?string $num_siret = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Societe $society = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    #[ORM\JoinColumn(nullable: true)]

    /**
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(name="creator_id", referencedColumnName="id")
     */
    private ?User $creator = null;

    #[ORM\Column(nullable: true)]

     /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Devis::class)]
    private Collection $devis;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Facture::class, orphanRemoval: true)]
    private Collection $factures;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->factures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(?string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getNumFix(): ?string
    {
        return $this->num_fix;
    }

    public function setNumFix(?string $num_fix): static
    {
        $this->num_fix = $num_fix;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(string $raison_sociale): static
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getNumSiret(): ?string
    {
        return $this->num_siret;
    }

    public function setNumSiret(string $num_siret): static
    {
        $this->num_siret = $num_siret;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getSociety(): ?Societe
    {
        return $this->society;
    }

    public function setSociety(?Societe $society): static
    {
        $this->society = $society;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): static
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setClient($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): static
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getClient() === $this) {
                $devi->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): static
    {
        if (!$this->factures->contains($facture)) {
            $this->factures->add($facture);
            $facture->setClient($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): static
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getClient() === $this) {
                $facture->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use App\Entity\soc\Societe;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Produit
{
    use Traits\TimestampableTrait;
    public const CATEGORIES = [
        'distanciel' => 'distanciel',
        'présentiel' => 'présentiel',
        'hybride' => 'hybride',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(
        message: 'Il faut renseigner la désignation du produit.'
    )]
    private ?string $designation = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_apprenant_min = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_apprenant_max = null;

    #[ORM\Column]
    #[Assert\NotBlank(
        message: 'Le prix unitaire ne doit pas être vide.'
    )]
    private ?float $price_unit = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(
        message: 'La catégorie ne doit pas être vide.'
    )]
    private ?string $categorie = null;

    #[ORM\Column]
    #[Assert\Type(
        type: 'float',
        message: 'La valeur de la tva doit etre sous format 0.2 par exemple pour 20%.'
    )]
    private ?float $taux_tva = null;


    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $exigeance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $certification = null;

    #[ORM\Column(unique: true)]
    #[Gedmo\Slug(fields: ['designation','id'])]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Societe $society = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: DevisProduit::class, orphanRemoval: true)]
    private Collection $devisProduits;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: FactureProduit::class, orphanRemoval: true)]
    private Collection $factureProduits;

    public function __construct()
    {
        $this->devisProduits = new ArrayCollection();
        $this->factureProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): static
    {
        $this->designation = $designation;

        return $this;
    }

    public function getNbApprenantMin(): ?int
    {
        return $this->nb_apprenant_min;
    }

    public function setNbApprenantMin(?int $nb_apprenant_min): static
    {
        $this->nb_apprenant_min = $nb_apprenant_min;

        return $this;
    }

    public function getNbApprenantMax(): ?int
    {
        return $this->nb_apprenant_max;
    }

    public function setNbApprenantMax(?int $nb_apprenant_max): static
    {
        $this->nb_apprenant_max = $nb_apprenant_max;

        return $this;
    }

    public function getPriceUnit(): ?float
    {
        return $this->price_unit;
    }

    public function setPriceUnit(float $price_unit): static
    {
        $this->price_unit = $price_unit;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getTauxTva(): ?float
    {
        return $this->taux_tva;
    }

    public function setTauxTva(float $taux_tva): static
    {
        $this->taux_tva = $taux_tva;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string|null $slug
     * @return self
     */
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getExigeance(): ?string
    {
        return $this->exigeance;
    }

    public function setExigeance(?string $exigeance): static
    {
        $this->exigeance = $exigeance;

        return $this;
    }

    public function getCertification(): ?string
    {
        return $this->certification;
    }

    public function setCertification(?string $certification): static
    {
        $this->certification = $certification;

        return $this;
    }

    public function getSociety(): ?Societe
    {
        return $this->society;
    }

    public function setSociety(?Societe $society): static
    {
        $this->society = $society;

        return $this;
    }


    

   

    /**
     * @return Collection<int, DevisProduit>
     */
    public function getDevisProduits(): Collection
    {
        return $this->devisProduits;
    }

    public function addDevisProduit(DevisProduit $devisProduit): static
    {
        if (!$this->devisProduits->contains($devisProduit)) {
            $this->devisProduits->add($devisProduit);
            $devisProduit->setProduct($this);
        }

        return $this;
    }

    public function removeDevisProduit(DevisProduit $devisProduit): static
    {
        if ($this->devisProduits->removeElement($devisProduit)) {
            // set the owning side to null (unless already changed)
            if ($devisProduit->getProduct() === $this) {
                $devisProduit->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, FactureProduit>
     */
    public function getFactureProduits(): Collection
    {
        return $this->factureProduits;
    }

    public function addFactureProduit(FactureProduit $factureProduit): static
    {
        if (!$this->factureProduits->contains($factureProduit)) {
            $this->factureProduits->add($factureProduit);
            $factureProduit->setProduct($this);
        }

        return $this;
    }

    public function removeFactureProduit(FactureProduit $factureProduit): static
    {
        if ($this->factureProduits->removeElement($factureProduit)) {
            // set the owning side to null (unless already changed)
            if ($factureProduit->getProduct() === $this) {
                $factureProduit->setProduct(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\soc\Societe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;



class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $options['user'];
        $builder
            ->add('designation')
            ->add('nb_apprenant_min')
            ->add('nb_apprenant_max')
            ->add('price_unit', null, [
                'label' => 'Prix unitaire',
                'attr' => ['class' => 'custom-class', 'placeholder' => 'Prix en euros']
            ])
            
            ->add('categorie', ChoiceType::class, [
                'choices' => Produit::CATEGORIES,
                'expanded' => false, 
                'multiple' => false, 
                'label' => 'Catégorie',
                'placeholder' => 'Séléctionner une catégorie',
            ])
            ->add('taux_tva')
            ->add('duration')
            ->add('exigeance')
            ->add('certification')
            ->add('society', EntityType::class, [ 
                'class' => Societe::class,
                'choices' => $user->getSocieteId()->toArray(), 
                'choice_label' => 'raisonSociale',
                'multiple' => false,
                'expanded' => false,
                'label' => 'Société',
                'placeholder' => 'Séléctionner une société',
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
            'user' => null, 
        ]);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    {% include 'components/navbar.html.twig' %}

    <div class="flex flex-wrap mt-4">
        {% include 'components/sidebar.html.twig' %}

        <div class="flex-grow p-4 bg-white dark:bg-gray-800 rounded-lg shadow ml-4 mr-4">
            <h1 class="mb-4 text-lg font-bold font-nunito text-blue-color dark:text-white">Modifier un produit</h1>

            <div>
                {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}
            </div>

            <div class="flex justify-end space-x-4 mt-4">
                <form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Etes vous sure de vouloir supprimer ce produit?');">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
                    <button class="px-4 py-2 bg-blue-color text-white rounded-lg">Delete</button>
                </form>
            </div>
            <a href="{{ path('app_produit_index') }}" class=" text-left text-blue-color hover:text-blue-600 dark:hover:text-blue-400 dark:text-white">
                <i class="fas fa-arrow-left"></i>
            </a>
        </div>
    </div>
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index des Produits{% endblock %}

{% block body %}
{% include 'components/navbar.html.twig' %}
<div class="flex mt-4">
    {% include 'components/sidebar.html.twig' %}
    <div class="ml-4 mr-4 flex-1 p-4 overflow-x-auto dark:bg-gray-800 content bg-white p-4 rounded-lg shadow">
        <h1 class="text-blue-color font-nunito text-lg font-bold dark:text-white mb-4">Gérer les produits</h1>
        <div class="mb-4">
            <form action="{{ path('app_produit_index') }}" method="get" class="flex items-center space-x-2">
                <input type="text" name="search" placeholder="Rechercher par designation" class="flex-1 border p-2 rounded-lg text-black dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400 w-full sm:w-auto sm:flex-1">
                <button type="submit" class="p-2 bg-blue-color text-white rounded-lg flex items-center justify-center w-12 h-12 sm:w-auto sm:h-auto sm:p-2">
                    <i class="fas fa-search text-white text-lg"></i>
                    <span class="ml-2 hidden sm:block">Rechercher</span>
                </button>
            </form>
        </div>
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-white font-nunito uppercase bg-blue-color">
                    <tr>
                        <th scope="col" class="px-6 py-3">Designation</th>
                        <th scope="col" class="px-6 py-3">Catégorie</th>
                        <th scope="col" class="px-6 py-3">Société</th>
                        <th scope="col" class="px-6 py-3">Créé le</th>
                        <th scope="col" class="px-6 py-3">Créé par</th>
                        <th scope="col" class="px-6 py-3">Modifié le</th>
                        <th scope="col" class="px-6 py-3">Modifié par</th>
                        <th scope="col" class="px-6 py-3">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for produit in produits %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <td class="px-6 py-4">{{ produit.designation }}</td>
                        <td class="px-6 py-4">{{ produit.categorie }}</td>
                        <td class="px-6 py-4">{{ produit.society ? produit.society.raisonSociale : 'Non associé' }}</td>
                        <td class="px-6 py-4">{{ produit.createdAt ? produit.createdAt|date('Y-m-d') : '' }}</td>
                        <td class="px-6 py-4">{{ produit.createdBy ? produit.createdBy.email : 'N/A' }}</td>
                        <td class="px-6 py-4">{{ produit.updatedAt ? produit.updatedAt|date('Y-m-d') : '' }}</td>
                        <td class="px-6 py-4">{{ produit.updatedBy ? produit.updatedBy.email : 'N/A' }}</td>
                        <td class="px-6 py-4 flex space-x-2">
                            <a href="{{ path('app_produit_show', {'slug': produit.slug}) }}" class="font-medium text-blue-600 hover:underline dark:text-blue-300">Voir</a>
                            <a href="{{ path('app_produit_edit', {'slug': produit.slug}) }}" class="font-medium text-blue-600 hover:underline dark:text-blue-300">Modifier</a>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="8" class="px-6 py-4 text-center dark:text-white">Aucun produit trouvé</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="paginationControls" class="flex justify-center mt-4 space-x-2">
            {% if currentPage > 1 %}
                <a href="{{ path('app_produit_index', {'page': currentPage - 1}) }}" class="text-blue-color hover:text-blue-800 dark:text-white">
                    <i class="fas fa-arrow-left"></i>
                </a>
            {% endif %}
            <span class="text-blue-color dark:text-white">{{ currentPage }}</span>
            {% if currentPage < maxPages %}
                <a href="{{ path('app_produit_index', {'page': currentPage + 1}) }}" class="text-blue-color hover:text-blue-800 dark:text-white">
                    <i class="fas fa-arrow-right"></i>
                </a>
            {% endif %}
        </div>

        <div class="mt-4">
            <a href="{{ path('app_produit_new') }}" class="px-4 py-2 bg-blue-color text-white rounded-lg float-right dark:text-gray-200">Créer un nouveau produit</a>
        </div>
    </div>
</div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    {% include 'components/navbar.html.twig' %}

    <div class="flex flex-wrap mt-4">
        {% include 'components/sidebar.html.twig' %}

        <div class="flex-grow p-4 bg-white dark:bg-gray-800 rounded-lg shadow ml-4 mr-4">
            <h1 class="mb-4 text-lg font-bold font-nunito text-blue-color dark:text-white">Créer un nouveau produit</h1>

            <div>
                {{ include('produit/_form.html.twig') }}
            </div>

            <a href="{{ path('app_produit_index') }}" class="text-blue-color hover:text-blue-600 dark:hover:text-blue-400 dark:text-white">
                <i class="fas fa-arrow-left"></i> Retour
            </a>
        </div>
    </div>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du Produit{% endblock %}

{% block body %}
    {% include 'components/navbar.html.twig' %}

    <div class="flex mt-4 ml-2">
        {% include 'components/sidebar.html.twig' %}
        
        <div class="flex-1 p-4 content bg-white dark:bg-gray-800 p-2 rounded-lg mr-4 ml-2 overflow-x-auto">
            <h1 class="text-blue-color font-nunito text-lg font-bold mb-2 dark:text-white">Détails du Produit</h1>
            
            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Désignation</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.designation }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Exigence</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.exigeance ? produit.exigeance : 'N/A' }}</div>
                </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Catégorie</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.categorie }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Société</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.society.raisonSociale }}</div>
                </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Prix Unitaire</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.priceUnit }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Taux TVA</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.tauxTva }}</div>
                </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-4 items-center mb-2">
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Nb Apprenant Min</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.nbApprenantMin ? produit.nbApprenantMin : 0 }}</div>
                </div>
                <div class="w-full sm:w-1/2">
                    <div class="mb-1 text-sm font-semibold font-nunito text-blue-color dark:text-white">Nb Apprenant Max</div>
                    <div class="border border-gray-200 bg-blue-color-opacity text-blue-color font-nunito p-2 rounded-lg w-full dark:bg-gray-700 dark:border-gray-700 dark:text-gray-400">{{ produit.nbApprenantMax ? produit.nbApprenantMax : 0 }}</div>
                </div>
            </div>

            <div class="text-left mt-4">
                <a href="{{ path('app_produit_index') }}" class="text-blue-color dark:text-white">
                    <i class="fas fa-arrow-left"></i> Retour
                </a>
            </div>
        </div>
    </div>
{% endblock %}